### PR TITLE
use configured  HTTP client  instead of curl

### PR DESCRIPTION
**Pull request by videni**
use configured  HTTP client  instead of curl,  make it consistant with other payment gateways

### CODE REVIEW

**Comment by lokielse** [comment]
@videni Thanks for PR, I'll replace all `Http::post` with `httpClient` sometime

**Comment by videni** [comment]
my pleasure, please do it quickly,   apply my PR where you try to do this,   even though something need to be fixed, it still can save you some time.

**Comment by lokielse** [comment]
@videni Code update with tag `v1.0.15`,  check it out!!

**Comment by videni** [comment]
@lokielse,very appreciate

**Pull request closed without merging**
